# Global Buy system settings
EnableBuyCommands = true
WeaponBuyZoneOnly = false                              # If true, players can only buy weapons in buy zones
AllowedTeamsToBuy = ["CounterTerrorist", "Terrorist"]  # Teams allowed to buy weapons

# Supported weapon data properties
# [WeaponDatas."weapon_name"]
# EnableBuyCommand              - Enable/disable buy commands for this weapon
# BuyAliases                    - Alternative names for buy commands (e.g., ["ak", "ak47", "kalash"])
# Clip                          - Sets weapon clip size
# Ammo                          - Sets weapon ammo count
# UnlimitedAmmo                 - Enables unlimited ammo (true/false)
# UnlimitedClip                 - Enables unlimited clip (true/false)

# Price                         - Base price for the weapon (if not set, defaults to game price)
# PriceScale                    - Price scaling factor for multiple purchases
# PriceScaleMultiplicative      - If true: price *= scale^count, if false: price += (price * scale * count)
#                                 e.g., PriceScaleMultiplicative = true, Price = 1000, PriceScale = 1.2
#                                 1st purchase: 1000, 2nd purchase: 1200, 3rd purchase: 1440, etc.
#                                 e.g., PriceScaleMultiplicative = false, Price = 1000, PriceScale = 0.2
#                                 1st purchase: 1000, 2nd purchase: 1200, 3rd purchase: 1400, etc.

[WeaponDatas]

# Pistols
[WeaponDatas.weapon_glock]
EnableBuyCommand = true

[WeaponDatas.weapon_usp_silencer]
EnableBuyCommand = true
BuyAliases = ["usp"]

[WeaponDatas.weapon_p250]
EnableBuyCommand = true

[WeaponDatas.weapon_tec9]
EnableBuyCommand = true
BuyAliases = ["tec"]

[WeaponDatas.weapon_elite]
EnableBuyCommand = true

[WeaponDatas.weapon_fiveseven]
EnableBuyCommand = true
BuyAliases = ["57"]

[WeaponDatas.weapon_cz75a]
EnableBuyCommand = true
BuyAliases = ["cz"]

[WeaponDatas.weapon_deagle]
EnableBuyCommand = true

[WeaponDatas.weapon_revolver]
EnableBuyCommand = false
BuyAliases = ["r8"]

# SMGs (Submachine Guns)
[WeaponDatas.weapon_mac10]
EnableBuyCommand = true
BuyAliases = ["mac"]

[WeaponDatas.weapon_mp9]
EnableBuyCommand = true

[WeaponDatas.weapon_mp5sd]
EnableBuyCommand = true
BuyAliases = ["mp5"]

[WeaponDatas.weapon_mp7]
EnableBuyCommand = true

[WeaponDatas.weapon_ump45]
EnableBuyCommand = true
BuyAliases = ["ump"]

[WeaponDatas.weapon_bizon]
EnableBuyCommand = true

[WeaponDatas.weapon_p90]
EnableBuyCommand = true

# Shotguns
[WeaponDatas.weapon_nova]
EnableBuyCommand = true

[WeaponDatas.weapon_xm1014]
EnableBuyCommand = true
BuyAliases = ["xm"]

[WeaponDatas.weapon_sawedoff]
EnableBuyCommand = true
BuyAliases = ["sawed"]

[WeaponDatas.weapon_mag7]
EnableBuyCommand = true

# Assault Rifles
[WeaponDatas.weapon_famas]
EnableBuyCommand = true

[WeaponDatas.weapon_galilar]
EnableBuyCommand = true
BuyAliases = ["galil"]

[WeaponDatas.weapon_m4a1]
EnableBuyCommand = true
BuyAliases = ["m4a4", "m4", "a4"]

[WeaponDatas.weapon_m4a1_silencer]
EnableBuyCommand = true
BuyAliases = ["m4a1s", "m4s", "a1", "1s"]

[WeaponDatas.weapon_ak47]
EnableBuyCommand = true
BuyAliases = ["ak"]

[WeaponDatas.weapon_aug]
EnableBuyCommand = true

[WeaponDatas.weapon_sg556]
EnableBuyCommand = true
BuyAliases = ["sg"]

# Sniper Rifles
[WeaponDatas.weapon_ssg08]
EnableBuyCommand = true
BuyAliases = ["scout", "ssg"]

[WeaponDatas.weapon_awp]
EnableBuyCommand = true

[WeaponDatas.weapon_g3sg1]
EnableBuyCommand = true
BuyAliases = ["g3"]

[WeaponDatas.weapon_scar20]
EnableBuyCommand = true
BuyAliases = ["scar"]

# Machine Guns
[WeaponDatas.weapon_m249]
EnableBuyCommand = true

[WeaponDatas.weapon_negev]
EnableBuyCommand = false

# Knife
[WeaponDatas.weapon_knife]
EnableBuyCommand = false

# Grenades
[WeaponDatas.weapon_hegrenade]
EnableBuyCommand = true
BuyAliases = ["he", "hegrenade", "nade"]

[WeaponDatas.weapon_flashbang]
EnableBuyCommand = false
BuyAliases = ["flash"]

[WeaponDatas.weapon_smokegrenade]
EnableBuyCommand = false
BuyAliases = ["smoke"]

[WeaponDatas.weapon_incgrenade]
EnableBuyCommand = false
BuyAliases = ["inc"]

[WeaponDatas.weapon_molotov]
EnableBuyCommand = true

[WeaponDatas.weapon_decoy]
EnableBuyCommand = false

# Equipment
[WeaponDatas.weapon_taser]
EnableBuyCommand = false
BuyAliases = ["zeus", "taser"]

[WeaponDatas.item_kevlar]
EnableBuyCommand = true
BuyAliases = ["kev", "kevlar", "armor", "vest"]
